# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protocols/proto/aartos_json.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'protocols/proto/aartos_json.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!protocols/proto/aartos_json.proto\x12\x0c\x65\x66\x64i.data.v2\"\xa8\x04\n\x0b\x41\x61rtosTrack\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\x0b\n\x03uid\x18\x03 \x01(\t\x12\x0f\n\x07lat_deg\x18\x04 \x01(\x01\x12\x0f\n\x07lon_deg\x18\x05 \x01(\x01\x12\x10\n\x08\x63\x61llsign\x18\x06 \x01(\t\x12\x1c\n\x0f\x61\x61rtos_category\x18\x07 \x01(\tH\x00\x88\x01\x01\x12\x1f\n\x12\x61\x61rtos_alert_level\x18\x08 \x01(\tH\x01\x88\x01\x01\x12\x1f\n\x12\x61\x61rtos_probability\x18\t \x01(\x01H\x02\x88\x01\x01\x12\x17\n\x0f\x61\x61rtos_zone_ids\x18\n \x03(\x03\x12\x16\n\tgeo_alt_m\x18\x0b \x01(\x01H\x03\x88\x01\x01\x12\x15\n\x08speed_ms\x18\x0c \x01(\x01H\x04\x88\x01\x01\x12\x18\n\x0bheading_deg\x18\r \x01(\x01H\x05\x88\x01\x01\x12%\n\x18\x61\x61rtos_predicted_lat_deg\x18\x0e \x01(\x01H\x06\x88\x01\x01\x12%\n\x18\x61\x61rtos_predicted_lon_deg\x18\x0f \x01(\x01H\x07\x88\x01\x01\x42\x12\n\x10_aartos_categoryB\x15\n\x13_aartos_alert_levelB\x15\n\x13_aartos_probabilityB\x0c\n\n_geo_alt_mB\x0b\n\t_speed_msB\x0e\n\x0c_heading_degB\x1b\n\x19_aartos_predicted_lat_degB\x1b\n\x19_aartos_predicted_lon_degb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocols.proto.aartos_json_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AARTOSTRACK']._serialized_start=52
  _globals['_AARTOSTRACK']._serialized_end=604
# @@protoc_insertion_point(module_scope)
