# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protocols/proto/cap.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'protocols/proto/cap.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19protocols/proto/cap.proto\x12\x0c\x65\x66\x64i.data.v2\"\xc5\x02\n\x08\x43\x61pAlert\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\x12\n\nidentifier\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x10\n\x08severity\x18\x05 \x01(\t\x12\x12\n\x05\x65vent\x18\x06 \x01(\tH\x00\x88\x01\x01\x12\x15\n\x08headline\x18\x07 \x01(\tH\x01\x88\x01\x01\x12\x18\n\x0b\x64\x65scription\x18\x08 \x01(\tH\x02\x88\x01\x01\x12\x16\n\teffective\x18\t \x01(\x01H\x03\x88\x01\x01\x12\x14\n\x07\x65xpires\x18\n \x01(\x01H\x04\x88\x01\x01\x12\x1a\n\rgeometry_json\x18\x0b \x01(\tH\x05\x88\x01\x01\x42\x08\n\x06_eventB\x0b\n\t_headlineB\x0e\n\x0c_descriptionB\x0c\n\n_effectiveB\n\n\x08_expiresB\x10\n\x0e_geometry_jsonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocols.proto.cap_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CAPALERT']._serialized_start=44
  _globals['_CAPALERT']._serialized_end=369
# @@protoc_insertion_point(module_scope)
