# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protocols/proto/flex335.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'protocols/proto/flex335.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protocols.proto import normalized_track_pb2 as protocols_dot_proto_dot_normalized__track__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dprotocols/proto/flex335.proto\x12\x11\x65\x66\x64i.protocols.v2\x1a&protocols/proto/normalized_track.proto\"\xb8\x04\n\x13SapientFlex335Track\x12,\n\x05track\x18\x01 \x01(\x0b\x32\x1d.efdi.data.v2.NormalizedTrack\x12\x1c\n\x14sapient_message_type\x18\x02 \x01(\t\x12\x11\n\tsensor_id\x18\x03 \x01(\t\x12\x16\n\tobject_id\x18\x04 \x01(\tH\x00\x88\x01\x01\x12\x1e\n\x11sapient_report_id\x18\x05 \x01(\tH\x01\x88\x01\x01\x12\x1a\n\rsapient_class\x18\x06 \x01(\tH\x02\x88\x01\x01\x12\x1a\n\x12sapient_node_types\x18\x07 \x03(\t\x12\x1a\n\rsapient_state\x18\x08 \x01(\tH\x03\x88\x01\x01\x12!\n\x14\x64\x65tection_confidence\x18\t \x01(\x01H\x04\x88\x01\x01\x12\x1f\n\x12sapient_alert_type\x18\n \x01(\tH\x05\x88\x01\x01\x12!\n\x14sapient_alert_status\x18\x0b \x01(\tH\x06\x88\x01\x01\x12#\n\x16sapient_alert_priority\x18\x0c \x01(\tH\x07\x88\x01\x01\x42\x0c\n\n_object_idB\x14\n\x12_sapient_report_idB\x10\n\x0e_sapient_classB\x10\n\x0e_sapient_stateB\x17\n\x15_detection_confidenceB\x15\n\x13_sapient_alert_typeB\x17\n\x15_sapient_alert_statusB\x19\n\x17_sapient_alert_priorityb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocols.proto.flex335_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SAPIENTFLEX335TRACK']._serialized_start=93
  _globals['_SAPIENTFLEX335TRACK']._serialized_end=661
# @@protoc_insertion_point(module_scope)
