# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protocols/proto/mission_route.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'protocols/proto/mission_route.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#protocols/proto/mission_route.proto\x12\x0c\x65\x66\x64i.data.v2\"\x8b\x03\n\x0cMissionRoute\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\x0b\n\x03uid\x18\x03 \x01(\t\x12\x13\n\x0b\x63oordinates\x18\x04 \x03(\x01\x12\x17\n\nroute_type\x18\x05 \x01(\tH\x00\x88\x01\x01\x12\x15\n\x08\x63\x61llsign\x18\x06 \x01(\tH\x01\x88\x01\x01\x12\x1d\n\x10lower_altitude_m\x18\x07 \x01(\x01H\x02\x88\x01\x01\x12\x1d\n\x10upper_altitude_m\x18\x08 \x01(\x01H\x03\x88\x01\x01\x12\x17\n\nvalid_from\x18\t \x01(\x01H\x04\x88\x01\x01\x12\x18\n\x0bvalid_until\x18\n \x01(\x01H\x05\x88\x01\x01\x12\x1c\n\x0fproperties_json\x18\x0b \x01(\tH\x06\x88\x01\x01\x42\r\n\x0b_route_typeB\x0b\n\t_callsignB\x13\n\x11_lower_altitude_mB\x13\n\x11_upper_altitude_mB\r\n\x0b_valid_fromB\x0e\n\x0c_valid_untilB\x12\n\x10_properties_jsonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocols.proto.mission_route_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MISSIONROUTE']._serialized_start=54
  _globals['_MISSIONROUTE']._serialized_end=449
# @@protoc_insertion_point(module_scope)
