# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protocols/proto/nffi.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'protocols/proto/nffi.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protocols.proto import normalized_track_pb2 as protocols_dot_proto_dot_normalized__track__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aprotocols/proto/nffi.proto\x12\x11\x65\x66\x64i.protocols.v2\x1a&protocols/proto/normalized_track.proto\"\xa6\x01\n\tNffiTrack\x12,\n\x05track\x18\x01 \x01(\x0b\x32\x1d.efdi.data.v2.NormalizedTrack\x12\x11\n\tsensor_id\x18\x02 \x01(\t\x12\x1d\n\x10nffi_affiliation\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x16\n\tunit_type\x18\x04 \x01(\tH\x01\x88\x01\x01\x42\x13\n\x11_nffi_affiliationB\x0c\n\n_unit_type\"9\n\x0eNffiRawIngress\x12\x11\n\tsource_id\x18\x01 \x01(\t\x12\x14\n\x0cxml_document\x18\x02 \x01(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocols.proto.nffi_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NFFITRACK']._serialized_start=90
  _globals['_NFFITRACK']._serialized_end=256
  _globals['_NFFIRAWINGRESS']._serialized_start=258
  _globals['_NFFIRAWINGRESS']._serialized_end=315
# @@protoc_insertion_point(module_scope)
