# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protocols/proto/normalized_track.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'protocols/proto/normalized_track.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&protocols/proto/normalized_track.proto\x12\x0c\x65\x66\x64i.data.v2\"\xf0\x05\n\x0fNormalizedTrack\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\x0b\n\x03uid\x18\x03 \x01(\t\x12\x15\n\x08\x63\x61llsign\x18\x04 \x01(\tH\x00\x88\x01\x01\x12\x1b\n\x0e\x63lassification\x18\x05 \x01(\tH\x01\x88\x01\x01\x12\x18\n\x0b\x61\x66\x66iliation\x18\x06 \x01(\tH\x02\x88\x01\x01\x12\x0f\n\x07lat_deg\x18\x07 \x01(\x01\x12\x0f\n\x07lon_deg\x18\x08 \x01(\x01\x12\x17\n\nbaro_alt_m\x18\t \x01(\x01H\x03\x88\x01\x01\x12\x16\n\tgeo_alt_m\x18\n \x01(\x01H\x04\x88\x01\x01\x12\x15\n\x08height_m\x18\x0b \x01(\x01H\x05\x88\x01\x01\x12\x15\n\x08speed_ms\x18\x0c \x01(\x01H\x06\x88\x01\x01\x12\x18\n\x0b\x61irspeed_ms\x18\r \x01(\x01H\x07\x88\x01\x01\x12\x18\n\x0bheading_deg\x18\x0e \x01(\x01H\x08\x88\x01\x01\x12\x1d\n\x10vertical_rate_ms\x18\x0f \x01(\x01H\t\x88\x01\x01\x12\x16\n\ton_ground\x18\x10 \x01(\x08H\n\x88\x01\x01\x12\x16\n\temergency\x18\x11 \x01(\x08H\x0b\x88\x01\x01\x12\x14\n\x07\x64\x65leted\x18\x12 \x01(\x08H\x0c\x88\x01\x01\x12J\n\x0fsource_metadata\x18\x13 \x03(\x0b\x32\x31.efdi.data.v2.NormalizedTrack.SourceMetadataEntry\x1a\x35\n\x13SourceMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x0b\n\t_callsignB\x11\n\x0f_classificationB\x0e\n\x0c_affiliationB\r\n\x0b_baro_alt_mB\x0c\n\n_geo_alt_mB\x0b\n\t_height_mB\x0b\n\t_speed_msB\x0e\n\x0c_airspeed_msB\x0e\n\x0c_heading_degB\x13\n\x11_vertical_rate_msB\x0c\n\n_on_groundB\x0c\n\n_emergencyB\n\n\x08_deletedb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocols.proto.normalized_track_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NORMALIZEDTRACK_SOURCEMETADATAENTRY']._loaded_options = None
  _globals['_NORMALIZEDTRACK_SOURCEMETADATAENTRY']._serialized_options = b'8\001'
  _globals['_NORMALIZEDTRACK']._serialized_start=57
  _globals['_NORMALIZEDTRACK']._serialized_end=809
  _globals['_NORMALIZEDTRACK_SOURCEMETADATAENTRY']._serialized_start=560
  _globals['_NORMALIZEDTRACK_SOURCEMETADATAENTRY']._serialized_end=613
# @@protoc_insertion_point(module_scope)
