# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protocols/proto/observation.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'protocols/proto/observation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!protocols/proto/observation.proto\x12\x0c\x65\x66\x64i.data.v2\"\xf7\x04\n\x0bObservation\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\x0b\n\x03uid\x18\x03 \x01(\t\x12\x16\n\tsensor_id\x18\x04 \x01(\tH\x00\x88\x01\x01\x12\x16\n\tobject_id\x18\x05 \x01(\tH\x01\x88\x01\x01\x12\x1b\n\x0e\x63lassification\x18\x06 \x01(\tH\x02\x88\x01\x01\x12\x18\n\x0b\x61\x66\x66iliation\x18\x07 \x01(\tH\x03\x88\x01\x01\x12\x14\n\x07lat_deg\x18\x08 \x01(\x01H\x04\x88\x01\x01\x12\x14\n\x07lon_deg\x18\t \x01(\x01H\x05\x88\x01\x01\x12\x17\n\naltitude_m\x18\n \x01(\x01H\x06\x88\x01\x01\x12\x18\n\x0b\x62\x65\x61ring_deg\x18\x0b \x01(\x01H\x07\x88\x01\x01\x12\x14\n\x07range_m\x18\x0c \x01(\x01H\x08\x88\x01\x01\x12\x17\n\nconfidence\x18\r \x01(\x01H\t\x88\x01\x01\x12\x17\n\naccuracy_m\x18\x0e \x01(\x01H\n\x88\x01\x01\x12\x13\n\x06status\x18\x0f \x01(\tH\x0b\x88\x01\x01\x12\x39\n\x08metadata\x18\x10 \x03(\x0b\x32\'.efdi.data.v2.Observation.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x0c\n\n_sensor_idB\x0c\n\n_object_idB\x11\n\x0f_classificationB\x0e\n\x0c_affiliationB\n\n\x08_lat_degB\n\n\x08_lon_degB\r\n\x0b_altitude_mB\x0e\n\x0c_bearing_degB\n\n\x08_range_mB\r\n\x0b_confidenceB\r\n\x0b_accuracy_mB\t\n\x07_statusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocols.proto.observation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OBSERVATION_METADATAENTRY']._loaded_options = None
  _globals['_OBSERVATION_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_OBSERVATION']._serialized_start=52
  _globals['_OBSERVATION']._serialized_end=683
  _globals['_OBSERVATION_METADATAENTRY']._serialized_start=465
  _globals['_OBSERVATION_METADATAENTRY']._serialized_end=512
# @@protoc_insertion_point(module_scope)
