# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protocols/proto/raw_envelope.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'protocols/proto/raw_envelope.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"protocols/proto/raw_envelope.proto\x12\x0c\x65\x66\x64i.data.v2\"\xa4\x02\n\x0bRawEnvelope\x12\x1a\n\x12received_timestamp\x18\x01 \x01(\x01\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\x10\n\x08protocol\x18\x03 \x01(\t\x12\x14\n\x07profile\x18\x04 \x01(\tH\x00\x88\x01\x01\x12\x16\n\ttransport\x18\x05 \x01(\tH\x01\x88\x01\x01\x12\x1b\n\x0esource_address\x18\x06 \x01(\tH\x02\x88\x01\x01\x12\x15\n\x08sequence\x18\x07 \x01(\x04H\x03\x88\x01\x01\x12\x0f\n\x07payload\x18\x08 \x01(\x0c\x12\x19\n\x0c\x63ontent_type\x18\t \x01(\tH\x04\x88\x01\x01\x42\n\n\x08_profileB\x0c\n\n_transportB\x11\n\x0f_source_addressB\x0b\n\t_sequenceB\x0f\n\r_content_typeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocols.proto.raw_envelope_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RAWENVELOPE']._serialized_start=53
  _globals['_RAWENVELOPE']._serialized_end=345
# @@protoc_insertion_point(module_scope)
