# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protocols/proto/sensor_health.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'protocols/proto/sensor_health.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#protocols/proto/sensor_health.proto\x12\x0c\x65\x66\x64i.data.v2\"\xd3\x03\n\x0cSensorHealth\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\x11\n\tsensor_id\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x12\n\x05model\x18\x05 \x01(\tH\x00\x88\x01\x01\x12\x15\n\x08\x66irmware\x18\x06 \x01(\tH\x01\x88\x01\x01\x12\x14\n\x07lat_deg\x18\x07 \x01(\x01H\x02\x88\x01\x01\x12\x14\n\x07lon_deg\x18\x08 \x01(\x01H\x03\x88\x01\x01\x12\x17\n\naltitude_m\x18\t \x01(\x01H\x04\x88\x01\x01\x12%\n\x18last_detection_timestamp\x18\n \x01(\x01H\x05\x88\x01\x01\x12\x13\n\x06\x64\x65tail\x18\x0b \x01(\tH\x06\x88\x01\x01\x12:\n\x08metadata\x18\x0c \x03(\x0b\x32(.efdi.data.v2.SensorHealth.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x08\n\x06_modelB\x0b\n\t_firmwareB\n\n\x08_lat_degB\n\n\x08_lon_degB\r\n\x0b_altitude_mB\x1b\n\x19_last_detection_timestampB\t\n\x07_detailb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocols.proto.sensor_health_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENSORHEALTH_METADATAENTRY']._loaded_options = None
  _globals['_SENSORHEALTH_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_SENSORHEALTH']._serialized_start=54
  _globals['_SENSORHEALTH']._serialized_end=521
  _globals['_SENSORHEALTH_METADATAENTRY']._serialized_start=372
  _globals['_SENSORHEALTH_METADATAENTRY']._serialized_end=419
# @@protoc_insertion_point(module_scope)
