# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protocols/proto/sparkplug.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'protocols/proto/sparkplug.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fprotocols/proto/sparkplug.proto\x12\x0c\x65\x66\x64i.data.v2\"\xbf\x03\n\x0fSparkplugRecord\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\x0b\n\x03uid\x18\x03 \x01(\t\x12\x0f\n\x07lat_deg\x18\x04 \x01(\x01\x12\x0f\n\x07lon_deg\x18\x05 \x01(\x01\x12\x15\n\x08group_id\x18\x06 \x01(\tH\x00\x88\x01\x01\x12\x19\n\x0c\x65\x64ge_node_id\x18\x07 \x01(\tH\x01\x88\x01\x01\x12\x16\n\tdevice_id\x18\x08 \x01(\tH\x02\x88\x01\x01\x12\x19\n\x0cmessage_type\x18\t \x01(\tH\x03\x88\x01\x01\x12\x10\n\x03seq\x18\n \x01(\x04H\x04\x88\x01\x01\x12\x16\n\tgeo_alt_m\x18\x0b \x01(\x01H\x05\x88\x01\x01\x12\x15\n\x08speed_ms\x18\x0c \x01(\x01H\x06\x88\x01\x01\x12\x18\n\x0bheading_deg\x18\r \x01(\x01H\x07\x88\x01\x01\x12\x19\n\x0cmetrics_json\x18\x0e \x01(\tH\x08\x88\x01\x01\x42\x0b\n\t_group_idB\x0f\n\r_edge_node_idB\x0c\n\n_device_idB\x0f\n\r_message_typeB\x06\n\x04_seqB\x0c\n\n_geo_alt_mB\x0b\n\t_speed_msB\x0e\n\x0c_heading_degB\x0f\n\r_metrics_jsonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocols.proto.sparkplug_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SPARKPLUGRECORD']._serialized_start=50
  _globals['_SPARKPLUGRECORD']._serialized_end=497
# @@protoc_insertion_point(module_scope)
