# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protocols/proto/weather_point.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'protocols/proto/weather_point.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#protocols/proto/weather_point.proto\x12\x0c\x65\x66\x64i.data.v2\"\xa4\x03\n\x0cWeatherPoint\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\x12\n\nplace_name\x18\x03 \x01(\t\x12\x12\n\nplace_code\x18\x04 \x01(\t\x12\x0f\n\x07lat_deg\x18\x05 \x01(\x01\x12\x0f\n\x07lon_deg\x18\x06 \x01(\x01\x12\x10\n\x08time_utc\x18\x07 \x01(\t\x12\x15\n\rtemperature_c\x18\x08 \x01(\x01\x12\x1e\n\x16\x61pparent_temperature_c\x18\t \x01(\x01\x12\x1d\n\x15relative_humidity_pct\x18\n \x01(\x05\x12\x18\n\x10precipitation_mm\x18\x0b \x01(\x01\x12\x15\n\rwind_speed_ms\x18\x0c \x01(\x01\x12\x1a\n\x12wind_direction_deg\x18\r \x01(\x05\x12\x15\n\rwind_gusts_ms\x18\x0e \x01(\x01\x12\x14\n\x0cweather_code\x18\x0f \x01(\x05\x12\x17\n\x0f\x63loud_cover_pct\x18\x10 \x01(\x05\x12\x14\n\x0cpressure_hpa\x18\x11 \x01(\x01\x12\x16\n\x0e\x63ondition_code\x18\x12 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocols.proto.weather_point_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WEATHERPOINT']._serialized_start=54
  _globals['_WEATHERPOINT']._serialized_end=474
# @@protoc_insertion_point(module_scope)
