#!/usr/bin/env bash
# EFDI — first-boot bring-up (run once per host, as root).
#
# Lays this pod's mTLS certs (generated by scripts/gen-certs.sh) into the Zenoh state dir,
# renders the router config from compose/.env, brings up the NetBird mesh link if configured,
# and starts the compose stack.
set -euo pipefail

POD_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${POD_DIR}/compose/.env"

[ "$(id -u)" -eq 0 ] || { echo "must run as root (cert + mesh privileges)"; exit 2; }
[ -f "$ENV_FILE" ] || { echo "no such file: ${ENV_FILE} — copy compose/.env.example first"; exit 2; }

for t in envsubst docker; do
  command -v "$t" >/dev/null 2>&1 || { echo "required tool not found on PATH: $t"; exit 2; }
done

set -a
# shellcheck disable=SC1090
source "$ENV_FILE"
set +a

: "${POD_STATE_DIR:=${POD_DIR}/compose/state}"
: "${BUNDLE_DIR:=${POD_DIR}/compose/certs}"
: "${ZENOH_LISTEN_PORT:=7447}"
: "${ZENOH_LOCAL_TCP_PORT:=7448}"
: "${ZENOH_VERIFY_NAME_ON_CONNECT:=false}"
: "${ZENOH_PLUGINS_LOADING_ENABLED:=true}"
: "${PARTNER_NAMESPACE:?PARTNER_NAMESPACE must be set in compose/.env}"
# INBOUND_NAMESPACE: bilateral prefix the fabric publishes TO the pod. Default to the pod's own
# namespace so the rendered ACL is always valid even when no bilateral inbound is granted yet.
: "${INBOUND_NAMESPACE:=${PARTNER_NAMESPACE}}"
: "${NAMESPACE_PREFIX:=LTU/CISB}"
NAMESPACE_ROOT="${NAMESPACE_PREFIX%%/*}"
: "${ZENOH_FABRIC_ENDPOINT:=}"

echo "==> EFDI first-boot (namespace=${PARTNER_NAMESPACE}, state=${POD_STATE_DIR})"

ZENOH_TLS_DIR="${POD_STATE_DIR}/zenoh/tls"
mkdir -p "${POD_STATE_DIR}/zenoh/rocksdb" "${ZENOH_TLS_DIR}"
chmod 700 "${POD_STATE_DIR}"

# --- [1/4] Lay this pod's Zenoh mTLS certs --------------------------------------------------------
echo "==> [1/4] laying Zenoh mTLS certs"
CERT_PATH="${BUNDLE_DIR}/${PARTNER_NAMESPACE}-cert.pem"
KEY_PATH="${BUNDLE_DIR}/${PARTNER_NAMESPACE}-key.pem"
CA_PATH="${BUNDLE_DIR}/efdi-ca-root.pem"
for f in "$CERT_PATH" "$KEY_PATH" "$CA_PATH"; do
  [ -f "$f" ] || { echo "missing ${f} — run scripts/gen-certs.sh ${PARTNER_NAMESPACE} first"; exit 1; }
done
install -m 600 "$CERT_PATH" "${ZENOH_TLS_DIR}/pod-cert.pem"
install -m 600 "$KEY_PATH"  "${ZENOH_TLS_DIR}/pod-key.pem"
install -m 644 "$CA_PATH"   "${ZENOH_TLS_DIR}/ca-roots.pem"

# --- [2/4] Render the pod Zenoh router config ----------------------------------------------------
echo "==> [2/4] rendering Zenoh router config"
ZENOH_CONNECT_ENDPOINTS="[]"
if [ -n "${ZENOH_FABRIC_ENDPOINT}" ]; then
  # shellcheck disable=SC2089  # JSON quotes are data consumed by envsubst.
  printf -v ZENOH_CONNECT_ENDPOINTS '["%s"]' "${ZENOH_FABRIC_ENDPOINT}"
fi
# shellcheck disable=SC2090  # Preserve the JSON string for envsubst below.
export ZENOH_LISTEN_PORT ZENOH_LOCAL_TCP_PORT ZENOH_CONNECT_ENDPOINTS PARTNER_NAMESPACE INBOUND_NAMESPACE NAMESPACE_PREFIX NAMESPACE_ROOT
export ZENOH_VERIFY_NAME_ON_CONNECT ZENOH_PLUGINS_LOADING_ENABLED
export POD_CERT_PEM="/etc/zenoh/tls/pod-cert.pem"   # in-container paths (compose mounts ZENOH_TLS_DIR ro)
export POD_KEY_PEM="/etc/zenoh/tls/pod-key.pem"
export CA_ROOTS_PEM="/etc/zenoh/tls/ca-roots.pem"
envsubst \
  '${ZENOH_LISTEN_PORT} ${ZENOH_LOCAL_TCP_PORT} ${ZENOH_CONNECT_ENDPOINTS} ${PARTNER_NAMESPACE} ${INBOUND_NAMESPACE} ${NAMESPACE_PREFIX} ${NAMESPACE_ROOT} ${ZENOH_VERIFY_NAME_ON_CONNECT} ${ZENOH_PLUGINS_LOADING_ENABLED} ${POD_CERT_PEM} ${POD_KEY_PEM} ${CA_ROOTS_PEM}' \
  < "${POD_DIR}/host/zenoh-router.json5.tmpl" \
  > "${POD_STATE_DIR}/zenoh/config.json5"
echo "    wrote ${POD_STATE_DIR}/zenoh/config.json5"
printf '%s\n' "${NAMESPACE_PREFIX}" > "${POD_STATE_DIR}/namespace-prefix"
echo "    wrote ${POD_STATE_DIR}/namespace-prefix (${NAMESPACE_PREFIX})"

# --- [3/4] Bring up the NetBird mesh link (optional) ----------------------------------------------
echo "==> [3/4] NetBird mesh"
if command -v netbird >/dev/null 2>&1; then
  if [ -n "${NETBIRD_SETUP_KEY:-}" ]; then
    netbird up --setup-key "${NETBIRD_SETUP_KEY}"
  else
    echo "    NETBIRD_SETUP_KEY not set in compose/.env — assuming netbird is already connected"
  fi
  netbird status || true
else
  echo "    netbird not installed — skipping mesh bring-up (router still binds locally on ${ZENOH_LISTEN_PORT}/${ZENOH_LOCAL_TCP_PORT})"
fi

# --- [4/4] Resolve the mesh IP for the audit-sink, then start the data plane ----------------------
echo "==> [4/4] starting the data plane"
# F-174: the audit-sink (a mode:client Zenoh peer with multicast scouting) cannot open a session
# against tls/127.0.0.1 — on network_mode:host it attempts a conflicting TLS listener on :7447
# which zenohd already owns ("Permission denied"). Point it at the router's mesh IP instead, if
# NetBird resolved one.
MESH_IP="$(netbird status 2>/dev/null | sed -n 's/.*NetBird IP:[[:space:]]*\([0-9.]*\).*/\1/p' | head -1)"
if [ -n "${MESH_IP}" ]; then
  echo "    mesh IP resolved: ${MESH_IP} — set ZENOH_LOCAL_ENDPOINT=tls/${MESH_IP}:${ZENOH_LISTEN_PORT} in compose/.env if not already (F-174)"
else
  echo "    mesh IP not resolved — ZENOH_LOCAL_ENDPOINT should stay tls/127.0.0.1:${ZENOH_LISTEN_PORT} (loopback) in compose/.env"
fi

( cd "${POD_DIR}/compose" && docker compose up -d )

echo "==> first-boot complete."
