#!/usr/bin/env bash
# EFDI — first-boot bring-up (run once per host, as root).
#
# Lays this pod's mTLS certs (generated by scripts/gen-certs.sh) into the Zenoh state dir,
# renders the router config from compose/.env, brings up the NetBird mesh link if configured,
# and starts the compose stack.
set -euo pipefail

POD_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${POD_DIR}/compose/.env"

[ "$(id -u)" -eq 0 ] || { echo "must run as root (cert + mesh privileges)"; exit 2; }
[ -f "$ENV_FILE" ] || { echo "no such file: ${ENV_FILE} — copy compose/.env.example first"; exit 2; }

for t in envsubst docker; do
  command -v "$t" >/dev/null 2>&1 || { echo "required tool not found on PATH: $t"; exit 2; }
done

set -a
# shellcheck disable=SC1090
source "$ENV_FILE"
set +a

: "${POD_STATE_DIR:=${POD_DIR}/compose/state}"
: "${BUNDLE_DIR:=${POD_DIR}/compose/certs}"
: "${ZENOH_LISTEN_PORT:=7447}"
: "${ZENOH_LOCAL_TCP_PORT:=7448}"
: "${ZENOH_VERIFY_NAME_ON_CONNECT:=false}"
: "${ZENOH_PLUGINS_LOADING_ENABLED:=true}"
: "${PARTNER_NAMESPACE:?PARTNER_NAMESPACE must be set in compose/.env}"
# INBOUND_NAMESPACE: bilateral prefix the fabric publishes TO the pod. Default to the pod's own
# namespace so the rendered ACL is always valid even when no bilateral inbound is granted yet.
: "${INBOUND_NAMESPACE:=${PARTNER_NAMESPACE}}"
: "${NAMESPACE_PREFIX:=EFDI}"
NAMESPACE_ROOT="${NAMESPACE_PREFIX%%/*}"
# Runtime data root is independently configurable. An explicitly empty value means that
# publishers use the slot itself (the live EFDI sandbox contract: <slot_id>/**).
if [[ ! -v DATA_NAMESPACE_PREFIX ]]; then
  DATA_NAMESPACE_PREFIX="${NAMESPACE_PREFIX}"
fi
if [[ -n "${DATA_NAMESPACE_PREFIX}" ]]; then
  DATA_TOPIC_ROOT="${DATA_NAMESPACE_PREFIX}/${PARTNER_NAMESPACE}"
else
  DATA_TOPIC_ROOT="${PARTNER_NAMESPACE}"
fi
# Backward-compatible single endpoint plus an optional JSON array for redundant uplinks and
# same-level links. The array is passed through only when it is explicitly configured.
: "${ZENOH_FABRIC_ENDPOINT:=}"
: "${ZENOH_FABRIC_ENDPOINTS:=}"

echo "==> EFDI first-boot (namespace=${PARTNER_NAMESPACE}, state=${POD_STATE_DIR})"

ZENOH_TLS_DIR="${POD_STATE_DIR}/zenoh/tls"
mkdir -p "${POD_STATE_DIR}/zenoh/rocksdb" "${ZENOH_TLS_DIR}"
chmod 700 "${POD_STATE_DIR}"

validate_runtime_identity() {
  local certificate="$1"
  local private_key="$2"
  local label="$3"
  command -v openssl >/dev/null 2>&1 || {
    echo "required tool not found on PATH: openssl (${label} profile is present)"
    exit 2
  }
  command -v cmp >/dev/null 2>&1 || {
    echo "required tool not found on PATH: cmp (${label} profile is present)"
    exit 2
  }
  openssl pkey -in "$private_key" -passin pass: -noout >/dev/null 2>&1 || {
    echo "${label} runtime key is encrypted or invalid: ${private_key}"
    exit 1
  }
  cmp -s \
    <(openssl pkey -in "$private_key" -passin pass: -pubout 2>/dev/null) \
    <(openssl x509 -in "$certificate" -pubkey -noout 2>/dev/null) || {
      echo "${label} certificate and private key do not match"
      exit 1
    }
}

# --- [1/4] Lay this pod's Zenoh mTLS certs --------------------------------------------------------
echo "==> [1/4] laying Zenoh mTLS certs"
CERT_BUNDLE_DIR="${BUNDLE_DIR}/efdi"
CERT_PATH="${CERT_BUNDLE_DIR}/${PARTNER_NAMESPACE}-cert.pem"
KEY_PATH="${CERT_BUNDLE_DIR}/${PARTNER_NAMESPACE}-key.pem"
CA_PATH="${CERT_BUNDLE_DIR}/efdi-ca-root.pem"
# Accept pre-folder-layout bundles during migration; new material is always
# generated under compose/certs/efdi by scripts/gen-certs.sh.
if [ ! -f "$CERT_PATH" ] || [ ! -f "$KEY_PATH" ] || [ ! -f "$CA_PATH" ]; then
  CERT_BUNDLE_DIR="$BUNDLE_DIR"
  CERT_PATH="${CERT_BUNDLE_DIR}/${PARTNER_NAMESPACE}-cert.pem"
  KEY_PATH="${CERT_BUNDLE_DIR}/${PARTNER_NAMESPACE}-key.pem"
  CA_PATH="${CERT_BUNDLE_DIR}/efdi-ca-root.pem"
fi
for f in "$CERT_PATH" "$KEY_PATH" "$CA_PATH"; do
  [ -f "$f" ] || { echo "missing ${f} — run scripts/gen-certs.sh ${PARTNER_NAMESPACE} first"; exit 1; }
done
install -m 600 "$CERT_PATH" "${ZENOH_TLS_DIR}/pod-cert.pem"
install -m 600 "$KEY_PATH"  "${ZENOH_TLS_DIR}/pod-key.pem"
install -m 644 "$CA_PATH"   "${ZENOH_TLS_DIR}/ca-roots.pem"

# Stage the optional Backbone client profile when its fixed-name bundle is
# present. The WebUI can then switch profiles without exposing source keys to
# the admin container or depending on machine-specific filenames.
BACKBONE_SOURCE="${BUNDLE_DIR}/efdi-backbone"
BACKBONE_RUNTIME="${ZENOH_TLS_DIR}/backbone"
if [ -e "${BACKBONE_SOURCE}/cert.pem" ] \
    || [ -e "${BACKBONE_SOURCE}/key.pem" ] \
    || [ -e "${BACKBONE_SOURCE}/ca-roots.pem" ]; then
  for f in cert.pem key.pem ca-roots.pem; do
    [ -f "${BACKBONE_SOURCE}/${f}" ] || {
      echo "incomplete Backbone bundle: missing ${BACKBONE_SOURCE}/${f}"
      exit 1
    }
  done
  validate_runtime_identity \
    "${BACKBONE_SOURCE}/cert.pem" "${BACKBONE_SOURCE}/key.pem" "Backbone"
  install -d -m 700 "${BACKBONE_RUNTIME}"
  install -m 644 "${BACKBONE_SOURCE}/cert.pem" "${BACKBONE_RUNTIME}/cert.pem"
  install -m 600 "${BACKBONE_SOURCE}/key.pem" "${BACKBONE_RUNTIME}/key.pem"
  install -m 644 "${BACKBONE_SOURCE}/ca-roots.pem" "${BACKBONE_RUNTIME}/ca-roots.pem"
  echo "    staged optional Backbone profile"
fi

# An LTU profile can also be discovered without a helper when the operator
# supplies a runtime-ready full chain and an unencrypted key. Encrypted source
# bundles still go through scripts/connect-ltu.sh so the passphrase is entered
# interactively and never stored in compose/.env or tracked files.
LTU_SOURCE="${BUNDLE_DIR}/efdi-ltu"
LTU_RUNTIME="${ZENOH_TLS_DIR}/ltu"
if [ -e "${LTU_SOURCE}/client-chain.pem" ]; then
  for f in client-chain.pem client.key ca.crt; do
    [ -f "${LTU_SOURCE}/${f}" ] || {
      echo "incomplete runtime-ready LTU bundle: missing ${LTU_SOURCE}/${f}"
      exit 1
    }
  done
  validate_runtime_identity \
    "${LTU_SOURCE}/client-chain.pem" "${LTU_SOURCE}/client.key" "LTU"
  install -d -m 700 "${LTU_RUNTIME}"
  install -m 644 "${LTU_SOURCE}/client-chain.pem" "${LTU_RUNTIME}/client-chain.pem"
  install -m 600 "${LTU_SOURCE}/client.key" "${LTU_RUNTIME}/client.key"
  install -m 644 "${LTU_SOURCE}/ca.crt" "${LTU_RUNTIME}/ca.crt"
  echo "    staged optional runtime-ready LTU profile"
fi

# --- [2/4] Render the pod Zenoh router config ----------------------------------------------------
echo "==> [2/4] rendering Zenoh router config"
ZENOH_CONNECT_ENDPOINTS="[]"
if [ -n "${ZENOH_FABRIC_ENDPOINTS}" ]; then
  case "${ZENOH_FABRIC_ENDPOINTS}" in
    \[*\]) ZENOH_CONNECT_ENDPOINTS="${ZENOH_FABRIC_ENDPOINTS}" ;;
    *) echo "ZENOH_FABRIC_ENDPOINTS must be a JSON array, for example [\"tls/100.64.0.2:7447\"]"; exit 2 ;;
  esac
elif [ -n "${ZENOH_FABRIC_ENDPOINT}" ]; then
  # shellcheck disable=SC2089  # JSON quotes are data consumed by envsubst.
  printf -v ZENOH_CONNECT_ENDPOINTS '["%s"]' "${ZENOH_FABRIC_ENDPOINT}"
fi
# shellcheck disable=SC2090  # Preserve the JSON string for envsubst below.
export ZENOH_LISTEN_PORT ZENOH_LOCAL_TCP_PORT ZENOH_CONNECT_ENDPOINTS PARTNER_NAMESPACE INBOUND_NAMESPACE NAMESPACE_PREFIX NAMESPACE_ROOT DATA_NAMESPACE_PREFIX DATA_TOPIC_ROOT
export ZENOH_VERIFY_NAME_ON_CONNECT ZENOH_PLUGINS_LOADING_ENABLED
export LISTEN_CERT_PEM="/etc/zenoh/tls/pod-cert.pem"   # in-container paths (compose mounts ZENOH_TLS_DIR ro)
export LISTEN_KEY_PEM="/etc/zenoh/tls/pod-key.pem"
export CONNECT_CERT_PEM="/etc/zenoh/tls/pod-cert.pem"
export CONNECT_KEY_PEM="/etc/zenoh/tls/pod-key.pem"
export CA_ROOTS_PEM="/etc/zenoh/tls/ca-roots.pem"
# shellcheck disable=SC2016  # envsubst requires literal variable names here.
envsubst \
  '${ZENOH_LISTEN_PORT} ${ZENOH_LOCAL_TCP_PORT} ${ZENOH_CONNECT_ENDPOINTS} ${PARTNER_NAMESPACE} ${INBOUND_NAMESPACE} ${NAMESPACE_PREFIX} ${NAMESPACE_ROOT} ${DATA_TOPIC_ROOT} ${ZENOH_VERIFY_NAME_ON_CONNECT} ${ZENOH_PLUGINS_LOADING_ENABLED} ${LISTEN_CERT_PEM} ${LISTEN_KEY_PEM} ${CONNECT_CERT_PEM} ${CONNECT_KEY_PEM} ${CA_ROOTS_PEM}' \
  < "${POD_DIR}/examples/zenoh-router.json5.tmpl" \
  > "${POD_STATE_DIR}/zenoh/config.json5"
echo "    wrote ${POD_STATE_DIR}/zenoh/config.json5"
printf '%s\n' "${NAMESPACE_PREFIX}" > "${POD_STATE_DIR}/namespace-prefix"
echo "    wrote ${POD_STATE_DIR}/namespace-prefix (${NAMESPACE_PREFIX})"
printf '%s\n' "${DATA_NAMESPACE_PREFIX}" > "${POD_STATE_DIR}/data-topic-prefix"
echo "    wrote ${POD_STATE_DIR}/data-topic-prefix (${DATA_NAMESPACE_PREFIX:-<slot-root>})"

# --- [3/4] Bring up the NetBird mesh link (optional) ----------------------------------------------
echo "==> [3/4] NetBird mesh"
if command -v netbird >/dev/null 2>&1; then
  if [ -n "${NETBIRD_SETUP_KEY:-}" ]; then
    netbird up --setup-key "${NETBIRD_SETUP_KEY}"
  else
    echo "    NETBIRD_SETUP_KEY not set in compose/.env — assuming netbird is already connected"
  fi
  netbird status || true
else
  echo "    netbird not installed — skipping mesh bring-up (router still binds locally on ${ZENOH_LISTEN_PORT}/${ZENOH_LOCAL_TCP_PORT})"
fi

# --- [4/4] Resolve the mesh IP for the audit-sink, then start the data plane ----------------------
echo "==> [4/4] starting the data plane"
# F-174: the audit-sink (a mode:client Zenoh peer with multicast scouting) cannot open a session
# against tls/127.0.0.1 — on network_mode:host it attempts a conflicting TLS listener on :7447
# which zenohd already owns ("Permission denied"). Point it at the router's mesh IP instead, if
# NetBird resolved one.
MESH_IP="$(netbird status 2>/dev/null | sed -n 's/.*NetBird IP:[[:space:]]*\([0-9.]*\).*/\1/p' | head -1)"
if [ -n "${MESH_IP}" ]; then
  echo "    mesh IP resolved: ${MESH_IP} — set ZENOH_LOCAL_ENDPOINT=tls/${MESH_IP}:${ZENOH_LISTEN_PORT} in compose/.env if not already (F-174)"
else
  echo "    mesh IP not resolved — ZENOH_LOCAL_ENDPOINT should stay tls/127.0.0.1:${ZENOH_LISTEN_PORT} (loopback) in compose/.env"
fi

( cd "${POD_DIR}/compose" && docker compose up -d )

echo "==> first-boot complete."
