#!/usr/bin/env python3
"""Reference: a must-deliver publisher (cache + miss-detection).

Illustrative, not production. A runnable shape of the "advanced publisher"
pattern — the native, cooperative answer for streams where a dropped sample
actually matters.

Context: delivery_reconcile.py covers the producer-side tiers for fire-and-forget
streams (self-canary, intent heartbeat). Its "Tier 3 — must-land messages" is
this file. The advanced publisher gives a continuous stream two guarantees a
plain `put` can't:

  * CACHE — the publisher keeps its recent samples and answers retransmission
            queries for its OWN keys. A subscriber that reconnects, or notices a
            gap, pulls the missing samples straight from you.
  * MISS-DETECTION — each sample carries a sequence number, and a periodic
            heartbeat advertises the latest one. A paired advanced subscriber can
            therefore tell *exactly* which samples it missed (by source + count),
            instead of guessing.
  * PUBLISHER-DETECTION — you advertise your presence (via liveliness), so a
            late-joining subscriber with detect_late_publishers can find you and
            pull your history.

Why this is NOT a broker (the thing the fabric deliberately avoids): the cache
lives in YOUR session and serves only YOUR keys. It is per-producer and
edge-local — there is no central component, no shared queue, no single
choke-point. Each producer carries the reliability for its own stream.

Cost/benefit: cache + heartbeat add memory and a little traffic. Use this for the
handful of streams that must not silently drop. For loss-tolerant telemetry,
stay on plain `put` (Tier 0) — over-confirming loads the fabric for no benefit.

Pair this with resilient_subscriber.py using RecoveryConfig(heartbeat=True) to
get true sequence-numbered recovery end to end.

Connection config comes from your pod operator (router endpoint + mTLS
cert/key/CA-roots, generated by scripts/gen-certs.sh):
  EFDI_ROUTER     e.g. tls/<router-host>:7447
  EFDI_MTLS_CERT  path to mtls.cert.pem
  EFDI_MTLS_KEY   path to mtls.key.pem
  EFDI_CA_ROOTS   path to ca-roots.pem
  PARTNER_NAMESPACE     your onboarded prefix, e.g. acme

Run:  python3 must_deliver_publisher.py
Deps: pip install eclipse-zenoh==1.9.0
"""

import json
import os
import time

import zenoh
import zenoh.ext


def open_session() -> zenoh.Session:
    """Open an mTLS client session against the EFDI router, from env config."""
    conf = zenoh.Config()
    conf.insert_json5("mode", json.dumps("client"))
    conf.insert_json5("connect/endpoints", json.dumps([os.environ["EFDI_ROUTER"]]))
    conf.insert_json5("transport/link/tls/root_ca_certificate",
                      json.dumps(os.environ["EFDI_CA_ROOTS"]))
    conf.insert_json5("transport/link/tls/connect_certificate",
                      json.dumps(os.environ["EFDI_MTLS_CERT"]))
    conf.insert_json5("transport/link/tls/connect_private_key",
                      json.dumps(os.environ["EFDI_MTLS_KEY"]))
    return zenoh.open(conf)


def main() -> None:
    prefix = os.environ["PARTNER_NAMESPACE"]
    session = open_session()

    key = f"{prefix}/critical/v1/status"

    publisher = zenoh.ext.declare_advanced_publisher(
        session,
        key,
        # Self-describing payloads (see self_describing_encoding.py).
        encoding=zenoh.Encoding.APPLICATION_JSON,
        # CACHE: retain the last 100 samples to answer retransmission queries
        # for this key. Size it to "how far behind can a subscriber fall and
        # still want to catch up" for your stream.
        cache=zenoh.ext.CacheConfig(max_samples=100),
        # MISS-DETECTION: emit a heartbeat every 1s carrying the latest sequence
        # number, so a paired subscriber recovers the last sample even on a quiet
        # stream. (heartbeat and sporadic_heartbeat are mutually exclusive.)
        sample_miss_detection=zenoh.ext.MissDetectionConfig(
            heartbeat=1.0, sporadic_heartbeat=None
        ),
        # PUBLISHER-DETECTION: advertise presence so late subscribers find us.
        publisher_detection=True,
    )

    print(f"[pub] advanced publisher on '{key}' (cache=100, heartbeat=1s). Ctrl-C to stop.")
    seq = 0
    try:
        while True:
            seq += 1
            body = json.dumps({"seq": seq, "ts_ms": int(time.time() * 1000),
                               "status": "nominal"}).encode()
            publisher.put(body)  # sequence-numbered + cached automatically
            if seq % 10 == 0:
                print(f"[pub] published {seq} samples (last {min(seq, 100)} recoverable from cache)")
            time.sleep(1)
    except KeyboardInterrupt:
        pass
    finally:
        publisher.undeclare()
        session.close()


if __name__ == "__main__":
    main()
