import re
from datetime import datetime, timezone
from fastapi import APIRouter, Depends
from fastapi.responses import Response
from pydantic import BaseModel, field_validator
from sqlalchemy.ext.asyncio import AsyncSession

from .db import get_db
from .deps import require_role, write_audit

router = APIRouter(prefix="/api/publish-script", tags=["publish-script"])

_SAFE_ENDPOINT_RE = re.compile(r"^[A-Za-z0-9._/:-]+$")
_SAFE_CN_RE = re.compile(r"^[A-Za-z0-9._-]+$")
_SAFE_PATH_RE = re.compile(r"^[A-Za-z0-9._/-]+$")
_MAX_ROWS = 50
_MAX_MESSAGE_LEN = 65536


class PublishRow(BaseModel):
    topic: str
    message: str
    count: int = 1
    interval_s: float = 0.0

    @field_validator("topic")
    @classmethod
    def _check_topic(cls, v: str) -> str:
        if not v.strip():
            raise ValueError("topic must not be empty")
        return v

    @field_validator("message")
    @classmethod
    def _check_message(cls, v: str) -> str:
        if len(v) > _MAX_MESSAGE_LEN:
            raise ValueError(f"message must be at most {_MAX_MESSAGE_LEN} characters")
        return v

    @field_validator("count")
    @classmethod
    def _check_count(cls, v: int) -> int:
        if v < 1:
            raise ValueError("count must be >= 1")
        return v

    @field_validator("interval_s")
    @classmethod
    def _check_interval(cls, v: float) -> float:
        if v < 0:
            raise ValueError("interval_s must be >= 0")
        return v


class PublishScriptRequest(BaseModel):
    router_endpoint: str
    client_cn: str
    cert_dir: str
    rows: list[PublishRow]

    @field_validator("router_endpoint")
    @classmethod
    def _check_endpoint(cls, v: str) -> str:
        if not _SAFE_ENDPOINT_RE.match(v):
            raise ValueError("router_endpoint: only letters, digits, '.', '_', '/', ':', '-' are allowed")
        return v

    @field_validator("client_cn")
    @classmethod
    def _check_cn(cls, v: str) -> str:
        if not _SAFE_CN_RE.match(v):
            raise ValueError("client_cn: only letters, digits, '.', '_', '-' are allowed")
        return v

    @field_validator("cert_dir")
    @classmethod
    def _check_cert_dir(cls, v: str) -> str:
        if not _SAFE_PATH_RE.match(v):
            raise ValueError("cert_dir: only letters, digits, '.', '_', '/', '-' are allowed")
        return v

    @field_validator("rows")
    @classmethod
    def _check_rows(cls, v: list[PublishRow]) -> list[PublishRow]:
        if not v:
            raise ValueError("at least one row is required")
        if len(v) > _MAX_ROWS:
            raise ValueError(f"at most {_MAX_ROWS} rows are allowed")
        return v


_TEMPLATE = '''#!/usr/bin/env python3
"""Generated by zenoh-admin's publish script builder — {generated_at}.

Standalone: needs only `pip install eclipse-zenoh==1.9.0` and the certs
referenced below. Safe to copy to any machine with mesh/pod reachability —
this script never touches the zenoh-admin GUI or API at runtime.
"""
import json
import time
import zenoh

ROUTER_ENDPOINT = {router_endpoint!r}
CLIENT_CN = {client_cn!r}
CERT_DIR = {cert_dir!r}

ROWS = {rows!r}


def make_config():
    conf = zenoh.Config()
    conf.insert_json5("mode", '"client"')
    conf.insert_json5("connect/endpoints", json.dumps([ROUTER_ENDPOINT]))
    if ROUTER_ENDPOINT.startswith("tls"):
        conf.insert_json5("transport/link/tls", json.dumps({{
            "root_ca_certificate": CERT_DIR + "/efdi-ca-root.pem",
            "connect_certificate": CERT_DIR + "/" + CLIENT_CN + "-cert.pem",
            "connect_private_key": CERT_DIR + "/" + CLIENT_CN + "-key.pem",
            "enable_mtls": True,
            "verify_name_on_connect": True,
        }}))
    return conf


def main():
    session = zenoh.open(make_config())
    print("Connected to", ROUTER_ENDPOINT, flush=True)
    try:
        for row in ROWS:
            topic, message = row["topic"], row["message"]
            count, interval_s = row["count"], row["interval_s"]
            pub = session.declare_publisher(topic)
            for i in range(count):
                pub.put(message.encode())
                preview = message if len(message) <= 80 else message[:80] + "..."
                print("[{{}}/{{}}] put {{}} -> {{!r}}".format(i + 1, count, topic, preview), flush=True)
                if i + 1 < count and interval_s > 0:
                    time.sleep(interval_s)
    finally:
        session.close()


if __name__ == "__main__":
    main()
'''


@router.post("")
async def generate_publish_script(
    req: PublishScriptRequest,
    db: AsyncSession = Depends(get_db),
    actor=Depends(require_role("superadmin")),
):
    rows_data = [
        {"topic": r.topic, "message": r.message, "count": r.count, "interval_s": r.interval_s}
        for r in req.rows
    ]
    script = _TEMPLATE.format(
        generated_at=datetime.now(timezone.utc).isoformat(),
        router_endpoint=req.router_endpoint,
        client_cn=req.client_cn,
        cert_dir=req.cert_dir,
        rows=rows_data,
    )

    topics = ", ".join(r.topic for r in req.rows)
    await write_audit(
        db, actor.id, "generate_publish_script",
        f"router={req.router_endpoint}, topics=[{topics}]",
    )

    return Response(
        content=script,
        media_type="text/x-python",
        headers={"Content-Disposition": 'attachment; filename="efdi_publish_script.py"'},
    )
