import os
import re
from datetime import datetime, timezone
from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import Response
from pydantic import BaseModel, field_validator, model_validator
from sqlalchemy.ext.asyncio import AsyncSession

from .db import get_db
from .deps import require_role, write_audit
from .config import CONFIG_PATH, _TLS_PROFILES, _extract_fields

router = APIRouter(prefix="/api/publish-script", tags=["publish-script"])

_SAFE_ENDPOINT_RE = re.compile(r"^[A-Za-z0-9._/:-]+$")
_SAFE_CN_RE = re.compile(r"^[A-Za-z0-9._-]+$")
_SAFE_PATH_RE = re.compile(r"^[A-Za-z0-9._/-]+$")
_MAX_ROWS = 50
_MAX_MESSAGE_LEN = 65536


class PublishRow(BaseModel):
    topic: str
    message: str
    count: int = 1
    interval_s: float = 0.0

    @field_validator("topic")
    @classmethod
    def _check_topic(cls, v: str) -> str:
        v = v.strip().strip("/")
        if not v:
            raise ValueError("topic must not be empty")
        if "*" in v:
            raise ValueError("publish topics must be concrete and cannot contain wildcards")
        return v

    @field_validator("message")
    @classmethod
    def _check_message(cls, v: str) -> str:
        if len(v) > _MAX_MESSAGE_LEN:
            raise ValueError(f"message must be at most {_MAX_MESSAGE_LEN} characters")
        return v

    @field_validator("count")
    @classmethod
    def _check_count(cls, v: int) -> int:
        if v < 1:
            raise ValueError("count must be >= 1")
        return v

    @field_validator("interval_s")
    @classmethod
    def _check_interval(cls, v: float) -> float:
        if v < 0:
            raise ValueError("interval_s must be >= 0")
        return v


class PublishScriptRequest(BaseModel):
    router_endpoint: str
    client_cn: str = ""
    cert_dir: str
    tls_profile: str = "efdi"
    verify_name_on_connect: bool = False
    rows: list[PublishRow]

    @field_validator("router_endpoint")
    @classmethod
    def _check_endpoint(cls, v: str) -> str:
        if not _SAFE_ENDPOINT_RE.fullmatch(v):
            raise ValueError("router_endpoint: only letters, digits, '.', '_', '/', ':', '-' are allowed")
        return v

    @field_validator("client_cn")
    @classmethod
    def _check_cn(cls, v: str) -> str:
        if v and not _SAFE_CN_RE.fullmatch(v):
            raise ValueError("client_cn: only letters, digits, '.', '_', '-' are allowed")
        return v

    @field_validator("cert_dir")
    @classmethod
    def _check_cert_dir(cls, v: str) -> str:
        if not _SAFE_PATH_RE.fullmatch(v):
            raise ValueError("cert_dir: only letters, digits, '.', '_', '/', '-' are allowed")
        return v

    @field_validator("tls_profile")
    @classmethod
    def _check_tls_profile(cls, v: str) -> str:
        if v not in _TLS_PROFILES:
            raise ValueError(f"unknown TLS profile: {v}")
        return v

    @field_validator("rows")
    @classmethod
    def _check_rows(cls, v: list[PublishRow]) -> list[PublishRow]:
        if not v:
            raise ValueError("at least one row is required")
        if len(v) > _MAX_ROWS:
            raise ValueError(f"at most {_MAX_ROWS} rows are allowed")
        return v

    @model_validator(mode="after")
    def _check_dynamic_certificate_name(self):
        profile = _TLS_PROFILES[self.tls_profile]
        filenames = (profile["publish_client_cert"], profile["publish_client_key"])
        if any("{client_cn}" in filename for filename in filenames) and not self.client_cn:
            raise ValueError("client_cn is required by the selected TLS profile")
        return self


_TEMPLATE = '''#!/usr/bin/env python3
"""Generated by zenoh-admin's publish script builder — {generated_at}.

Standalone: needs only `pip install eclipse-zenoh==1.9.0` and the certs
referenced below. Safe to copy to any machine with mesh/pod reachability —
this script never touches the zenoh-admin GUI or API at runtime.
"""
import json
import time
import zenoh

ROUTER_ENDPOINT = {router_endpoint!r}
CERT_DIR = {cert_dir!r}
TLS_PROFILE = {tls_profile!r}
CERT_SUBDIR = {cert_subdir!r}
ROOT_CA_FILENAME = {root_ca_filename!r}
CLIENT_CERT_FILENAME = {client_cert_filename!r}
CLIENT_KEY_FILENAME = {client_key_filename!r}
VERIFY_NAME_ON_CONNECT = {verify_name_on_connect!r}

ROWS = {rows!r}


def make_config():
    conf = zenoh.Config()
    conf.insert_json5("mode", '"client"')
    conf.insert_json5("connect/endpoints", json.dumps([ROUTER_ENDPOINT]))
    if ROUTER_ENDPOINT.startswith("tls"):
        conf.insert_json5("transport/link/tls", json.dumps({{
            "root_ca_certificate": CERT_DIR + "/" + CERT_SUBDIR + "/" + ROOT_CA_FILENAME,
            "connect_certificate": CERT_DIR + "/" + CERT_SUBDIR + "/" + CLIENT_CERT_FILENAME,
            "connect_private_key": CERT_DIR + "/" + CERT_SUBDIR + "/" + CLIENT_KEY_FILENAME,
            "enable_mtls": True,
            "verify_name_on_connect": VERIFY_NAME_ON_CONNECT,
        }}))
    return conf


def main():
    session = zenoh.open(make_config())
    print("Connected to", ROUTER_ENDPOINT, flush=True)
    try:
        for row in ROWS:
            topic, message = row["topic"], row["message"]
            count, interval_s = row["count"], row["interval_s"]
            pub = session.declare_publisher(topic)
            for i in range(count):
                pub.put(message.encode())
                preview = message if len(message) <= 80 else message[:80] + "..."
                print("[{{}}/{{}}] put {{}} -> {{!r}}".format(i + 1, count, topic, preview), flush=True)
                if i + 1 < count and interval_s > 0:
                    time.sleep(interval_s)
    finally:
        session.close()


if __name__ == "__main__":
    main()
'''


def _profile_details(name: str, client_cn: str) -> dict[str, object]:
    profile = _TLS_PROFILES[name]
    return {
        "id": name,
        "label": profile["label"],
        "cert_subdir": profile["publish_cert_dir"],
        "root_ca_filename": profile["publish_root_ca"],
        "client_cert_filename": profile["publish_client_cert"].format(client_cn=client_cn),
        "client_key_filename": profile["publish_client_key"].format(client_cn=client_cn),
        "router_connect_certificate": profile["connect_certificate"],
        "router_connect_private_key": profile["connect_private_key"],
        "router_root_ca": profile["root_ca"],
        "requires_client_cn": any(
            "{client_cn}" in filename
            for filename in (profile["publish_client_cert"], profile["publish_client_key"])
        ),
    }


def _publish_root(fields) -> str:
    namespace = (
        os.environ.get("PARTNER_NAMESPACE", "").strip("/")
        or fields.partner_namespace.strip("/")
    )
    if fields.fabric_tls_profile == "ltu-local":
        return namespace
    return "/".join(
        part
        for part in (fields.publish_prefix.strip("/"), namespace)
        if part
    )


@router.get("/defaults")
async def get_publish_defaults(_=Depends(require_role("superadmin"))):
    if not os.path.isfile(CONFIG_PATH):
        raise HTTPException(status_code=404, detail=f"Config file not found at {CONFIG_PATH}")
    try:
        with open(CONFIG_PATH, encoding="utf-8") as handle:
            fields = _extract_fields(handle.read())
    except (OSError, ValueError, KeyError, TypeError) as exc:
        raise HTTPException(status_code=500, detail=f"Could not parse current config: {exc}") from exc
    current_profile = _TLS_PROFILES[fields.fabric_tls_profile]
    requires_client_cn = any(
        "{client_cn}" in filename
        for filename in (
            current_profile["publish_client_cert"],
            current_profile["publish_client_key"],
        )
    )
    client_cn = (
        fields.partner_namespace or os.environ.get("PARTNER_NAMESPACE", "")
    ) if requires_client_cn else ""
    profile = _profile_details(fields.fabric_tls_profile, client_cn)
    profiles = [_profile_details(name, client_cn) for name in _TLS_PROFILES]
    return {
        "current_endpoint": fields.fabric_endpoints[0] if fields.fabric_endpoints else fields.fabric_endpoint,
        "endpoints": fields.fabric_endpoints,
        "publish_root": _publish_root(fields),
        "tls_profile": fields.fabric_tls_profile,
        "verify_name_on_connect": fields.verify_name_on_connect,
        "client_cn": client_cn,
        "cert_dir": os.environ.get("EFDI_CERT_HOST_DIR", ""),
        "profile": profile,
        "profiles": profiles,
        "config_path": CONFIG_PATH,
    }


@router.post("")
async def generate_publish_script(
    req: PublishScriptRequest,
    db: AsyncSession = Depends(get_db),
    actor=Depends(require_role("superadmin")),
):
    rows_data = [
        {"topic": r.topic, "message": r.message, "count": r.count, "interval_s": r.interval_s}
        for r in req.rows
    ]
    profile = _profile_details(req.tls_profile, req.client_cn)
    script = _TEMPLATE.format(
        generated_at=datetime.now(timezone.utc).isoformat(),
        router_endpoint=req.router_endpoint,
        cert_dir=req.cert_dir,
        tls_profile=req.tls_profile,
        verify_name_on_connect=req.verify_name_on_connect,
        cert_subdir=profile["cert_subdir"],
        root_ca_filename=profile["root_ca_filename"],
        client_cert_filename=profile["client_cert_filename"],
        client_key_filename=profile["client_key_filename"],
        rows=rows_data,
    )

    topics = ", ".join(r.topic for r in req.rows)
    await write_audit(
        db, actor.id, "generate_publish_script",
        f"router={req.router_endpoint}, topics=[{topics}]",
    )

    return Response(
        content=script,
        media_type="text/x-python",
        headers={"Content-Disposition": 'attachment; filename="efdi_publish_script.py"'},
    )
